version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: prism-postgres
    restart: always
    environment:
      POSTGRES_USER: prism_user
      POSTGRES_PASSWORD: prism_pass
      POSTGRES_DB: prism_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prism-network

volumes:
  postgres_data:

networks:
  prism-network:
    driver: bridge
